### ISSUE TITLE
Keys with `_` get wrapped by quotes

### ISSUE THREAD

**Issue by aur3l14no** [euank/yaml2nix#4]
`container_name: hello_world` would become `"container_name": "hello_world";` which stands out among other unquoted keys. Do you think it would be nice to remove those quotes?

**Comment by aur3l14no** [comment]
Though `sed 's/"\([^=;]*\)" =/\1 =/g'` is good enough maybe.

**Comment by euank** [comment]
Thanks for the suggestion, not quoting that definitely feels cleaner!

I've put up a PR which I think should quote the minimum number of attribute keys: #5 

For example, from the testdata file in that PR:

```yaml
x:
  unquoted_key_with_underscores: value
  "unquoted-key_with-quote'": 1
```

becomes

```nix
{ x = { unquoted_key_with_underscores = "value"; unquoted-key_with-quote' = 1; }; }
```

I'll plan to merge that and tag a release sometime soon
