### ISSUE TITLE
Wrap special keys in quotes

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [euank/yaml2nix#7]
`if`, `then`, `else,` and maybe others are not allowed to be unquoted attrbute keys, they should be quoted.

Use case: migrating Home Assistant configuration, which make heavy use of those.

**Comment by euank** [comment]
Thanks for the report!

I grabbed this list of keywords from the upstream nix lexer and made it so they all get quoted when used as map keys: https://github.com/NixOS/nix/blob/48477d4a3e7130c89b2ded4496c00ef74601091f/src/libexpr/lexer.l#L109-L118

Hopefully that covers all of em, let me know if you run into any others in practice!
